CREATE TABLE `{prefix}_{dirname}_lists` (
  `lists_id` int(11) unsigned NOT NULL  auto_increment,
  `category_id` mediumint(8) unsigned NOT NULL,
  `site` varchar(255) NOT NULL,
  `title` varchar(255) NOT NULL,
  `id` int(11) unsigned NOT NULL,
  `service_name` varchar(255) NOT NULL,
  `floor_name` varchar(255) NOT NULL,
  `category_name` varchar(255) NOT NULL,
  `content_id` varchar(255) NOT NULL,
  `product_id` varchar(255) NOT NULL,
  `url` varchar(255) NOT NULL,
  `affiliateURL` varchar(255) NOT NULL,
  `imageURL_list` varchar(255) NOT NULL,
  `imageURL_small` varchar(255) NOT NULL,
  `imageURL_large` varchar(255) NOT NULL,
  `sampleImageS0` varchar(255) NOT NULL,
  `sampleImageS1` varchar(255) NOT NULL,
  `sampleImageS2` varchar(255) NOT NULL,
  `sampleImageS3` varchar(255) NOT NULL,
  `sampleImageS4` varchar(255) NOT NULL,
  `sampleImageS5` varchar(255) NOT NULL,
  `sampleImageS6` varchar(255) NOT NULL,
  `sampleImageS7` varchar(255) NOT NULL,
  `sampleImageS8` varchar(255) NOT NULL,
  `sampleImageS9` varchar(255) NOT NULL,
  `movie_tag` text NOT NULL,
  `price` varchar(255) NOT NULL,
  `list_price` varchar(255) NOT NULL,
  `date` int(11) unsigned NOT NULL,
  `iteminfo_series_name` varchar(255) NOT NULL,
  `iteminfo_maker_name` varchar(255) NOT NULL,
  `posttime` int(11) unsigned NOT NULL,
  PRIMARY KEY  (`lists_id`)) ENGINE=MyISAM;

